import type { ComponentType } from 'react'
import {
  AbsencesGlyph,
  AcademyGlyph,
  AccueilGlyph,
  AnalyticsGlyph,
  BellGlyph,
  BirthdayGlyph,
  BlockedGlyph,
  ClockGlyph,
  ConsoleGlyph,
  CopyGlyph,
  DarkGlyph,
  DatabaseGlyph,
  DeadlineGlyph,
  DiscordFunctionGlyph,
  DiscordGlyph,
  DispositifGlyph,
  EditGlyph,
  EmojiGlyph,
  GlossaryGlyph,
  HelpGlyph,
  HiddenGlyph,
  HistoryGlyph,
  JournalGlyph,
  KeyGlyph,
  LeadGlyph,
  LightGlyph,
  LiveconGlyph,
  LockGlyph,
  MailGlyph,
  MeetingsGlyph,
  MembersGlyph,
  MetricsGlyph,
  NoteGlyph,
  ObjectiveGlyph,
  PhoneGlyph,
  PlatformGlyph,
  ProjectsGlyph,
  QueueGlyph,
  RecruitmentGlyph,
  RefreshGlyph,
  RemoveGlyph,
  SanctionsGlyph,
  ScanGlyph,
  SearchGlyph,
  SettingsGlyph,
  SheetGlyph,
  ShieldGlyph,
  SignOutGlyph,
  SkillGlyph,
  SparkGlyph,
  StarGlyph,
  StorageGlyph,
  SystemGlyph,
  TasksGlyph,
  TwoFactorGlyph,
  UnlockGlyph,
  VisibleGlyph,
  YoutuberGlyph,
  YoutuberNoneGlyph,
  CheckGlyph,
  AnimatorFunctionGlyph,
  LiveFunctionGlyph,
  RecruiterFunctionGlyph,
  TrainerFunctionGlyph,
  LiveconCalmGlyph,
  LiveconWatchGlyph,
  LiveconCrisisGlyph,
} from '@/components/elements/display/BrandGlyphs'
import {
  AddGlyph,
  BackGlyph,
  BoldGlyph,
  BulletGlyph,
  BulletListGlyph,
  BulletRingGlyph,
  CheckboxGlyph,
  CloseGlyph,
  CodeBlockGlyph,
  CodeGlyph,
  ConfirmGlyph,
  CrownGlyph,
  DangerGlyph,
  DivisionGlyph,
  DragGlyph,
  FailureGlyph,
  FilterGlyph,
  FlameGlyph,
  FlashGlyph,
  ForwardGlyph,
  HeadingGlyph,
  InfoGlyph,
  InheritGlyph,
  ItalicGlyph,
  LinkGlyph,
  MenuGlyph,
  MoreGlyph,
  NextGlyph,
  OrderedListGlyph,
  PendingGlyph,
  QuoteGlyph,
  ShieldOutlineGlyph,
  SortGlyph,
  StrikeGlyph,
  SuccessGlyph,
  TrailChevron,
  UnderlineGlyph,
  WarningGlyph,
  ClimbGlyph,
  DropGlyph,
  ParagraphGlyph,
  RuleGlyph,
} from '@/components/elements/display/Glyphs'
import {
  LiveDotGlyph,
  TwitchGlyph,
  YoutubeGlyph,
  ModDeleteGlyph,
  ModTimeoutGlyph,
  ModBanGlyph,
  ModUnbanGlyph,
  ModWarnGlyph,
  AutoModGlyph,
  ShieldModeGlyph,
  SlowModeGlyph,
  EmoteModeGlyph,
  FollowerModeGlyph,
  SubscriberModeGlyph,
  BlockedTermsGlyph,
  BroadcasterGlyph,
  VipGlyph,
  ChatBotGlyph,
  ViewerGlyph,
  ChatGlyph,
  StreamGlyph,
  ModActionsGlyph,
  UnbanRequestGlyph,
  CoordinatorGlyph,
  SanctionsPanelGlyph,
} from '@/components/elements/display/LiveGlyphs'

// Widened for brand glyphs
export type LucideIcon = ComponentType<{ className?: string } & Record<string, unknown>>

/**
 * Icons used across the interface
 * @type {Record<string, LucideIcon>}
 */

export const ICONS = {
  twoFactor: TwoFactorGlyph,
  dashboard: AccueilGlyph,
  members: MembersGlyph,
  recruitment: RecruitmentGlyph,
  teams: MembersGlyph,
  projects: ProjectsGlyph,
  tasks: TasksGlyph,
  meetings: MeetingsGlyph,
  absences: AbsencesGlyph,
  livecon: LiveconGlyph,
  liveconCalm: LiveconCalmGlyph,
  liveconWatch: LiveconWatchGlyph,
  liveconCrisis: LiveconCrisisGlyph,
  liveDot: LiveDotGlyph,
  twitch: TwitchGlyph,
  youtube: YoutubeGlyph,
  modDelete: ModDeleteGlyph,
  modTimeout: ModTimeoutGlyph,
  modBan: ModBanGlyph,
  modUnban: ModUnbanGlyph,
  modWarn: ModWarnGlyph,
  automod: AutoModGlyph,
  modeShield: ShieldModeGlyph,
  modeSlow: SlowModeGlyph,
  modeEmotes: EmoteModeGlyph,
  modeFollowers: FollowerModeGlyph,
  modeSubscribers: SubscriberModeGlyph,
  blockedTerms: BlockedTermsGlyph,
  broadcaster: BroadcasterGlyph,
  vip: VipGlyph,
  chatBot: ChatBotGlyph,
  viewer: ViewerGlyph,
  chat: ChatGlyph,
  stream: StreamGlyph,
  modActions: ModActionsGlyph,
  unbanRequest: UnbanRequestGlyph,
  coordinator: CoordinatorGlyph,
  sanctionsPanel: SanctionsPanelGlyph,
  academy: AcademyGlyph,
  glossary: GlossaryGlyph,
  skill: SkillGlyph,
  objective: ObjectiveGlyph,
  dispositif: DispositifGlyph,
  sanctions: SanctionsGlyph,
  lead: LeadGlyph,
  console: ConsoleGlyph,
  flash: FlashGlyph,
  settings: SettingsGlyph,
  search: SearchGlyph,
  youtuber: YoutuberGlyph,
  youtuberNone: YoutuberNoneGlyph,
  discord: DiscordGlyph,
  platform: PlatformGlyph,
  division: DivisionGlyph,
  note: NoteGlyph,
  bell: BellGlyph,
  history: HistoryGlyph,
  refresh: RefreshGlyph,
  sheet: SheetGlyph,
  shield: ShieldGlyph,
  shieldOutline: ShieldOutlineGlyph,
  flame: FlameGlyph,
  crown: CrownGlyph,
  // One per fixed function, keyed as its row stores it
  functionDiscord: DiscordFunctionGlyph,
  functionLive: LiveFunctionGlyph,
  functionAnimator: AnimatorFunctionGlyph,
  functionRecruiter: RecruiterFunctionGlyph,
  functionTrainer: TrainerFunctionGlyph,
  lock: LockGlyph,
  unlock: UnlockGlyph,
  key: KeyGlyph,
  scan: ScanGlyph,
  database: DatabaseGlyph,
  queue: QueueGlyph,
  storage: StorageGlyph,
  metrics: MetricsGlyph,
  analytics: AnalyticsGlyph,
  journal: JournalGlyph,
  alert: SanctionsGlyph,
  add: AddGlyph,
  edit: EditGlyph,
  remove: RemoveGlyph,
  close: CloseGlyph,
  confirm: ConfirmGlyph,
  picked: CheckGlyph,
  copy: CopyGlyph,
  link: LinkGlyph,
  filter: FilterGlyph,
  sort: SortGlyph,
  drag: DragGlyph,
  next: NextGlyph,
  climb: ClimbGlyph,
  paragraph: ParagraphGlyph,
  rule: RuleGlyph,
  drop: DropGlyph,
  expand: TrailChevron,
  more: MoreGlyph,
  menu: MenuGlyph,
  forward: ForwardGlyph,
  back: BackGlyph,
  signOut: SignOutGlyph,
  light: LightGlyph,
  dark: DarkGlyph,
  system: SystemGlyph,
  visible: VisibleGlyph,
  hidden: HiddenGlyph,
  star: StarGlyph,
  spark: SparkGlyph,
  emoji: EmojiGlyph,
  clock: ClockGlyph,
  deadline: DeadlineGlyph,
  mail: MailGlyph,
  phone: PhoneGlyph,
  birthday: BirthdayGlyph,
  info: InfoGlyph,
  warning: WarningGlyph,
  danger: DangerGlyph,
  success: SuccessGlyph,
  failure: FailureGlyph,
  help: HelpGlyph,
  blocked: BlockedGlyph,
  pending: PendingGlyph,
  checkbox: CheckboxGlyph,
  inherit: InheritGlyph,
  bold: BoldGlyph,
  italic: ItalicGlyph,
  underline: UnderlineGlyph,
  strike: StrikeGlyph,
  heading: HeadingGlyph,
  quote: QuoteGlyph,
  bulletList: BulletListGlyph,
  bullet: BulletGlyph,
  bulletRing: BulletRingGlyph,
  orderedList: OrderedListGlyph,
  code: CodeGlyph,
  codeBlock: CodeBlockGlyph,
} as const satisfies Record<string, LucideIcon>

export type IconName = keyof typeof ICONS

/**
 * Every icon key, in declaration order
 * @type {IconName[]}
 */

export const ICON_NAMES = Object.keys(ICONS) as IconName[]

/**
 * Check a known icon key
 * @param {string} value - Candidate key
 * @return {boolean} - Known icon
 */

export const isIconName = (value: string): value is IconName => value in ICONS
