import {
  AlarmClock,
  ArrowLeft,
  ArrowRight,
  ArrowUpDown,
  Ban,
  Bold,
  BookOpen,
  Cake,
  CalendarDays,
  CalendarOff,
  Check,
  ChevronDown,
  ChevronRight,
  ChevronsRight,
  CircleAlert,
  CircleCheck,
  CircleHelp,
  CircleX,
  Clock,
  Code,
  Copy,
  Eye,
  EyeOff,
  FileText,
  Filter,
  FolderKanban,
  Flag,
  Gavel,
  GraduationCap,
  GripVertical,
  Hash,
  Heading2,
  History,
  Info,
  Italic,
  LayoutDashboard,
  Link2,
  ListChecks,
  ListOrdered,
  List as ListIcon,
  Loader,
  LogOut,
  Mail,
  MessageSquare,
  Monitor,
  MonitorPlay,
  Moon,
  Pencil,
  Phone,
  Plus,
  Quote,
  Radio,
  Route,
  Search,
  Settings,
  Shield,
  ShieldAlert,
  Sparkles,
  Square,
  SquareCode,
  Star,
  StickyNote,
  Strikethrough,
  Smile,
  Sun,
  Target,
  Trash2,
  TriangleAlert,
  Underline,
  Users,
  UserPlus,
  UsersRound,
  X,
  Zap,
} from 'lucide-react'
import type { LucideIcon } from 'lucide-react'

/**
 * Icons used across the interface
 * @type {Record<string, LucideIcon>}
 */

export const ICONS = {
  dashboard: LayoutDashboard,
  members: Users,
  recruitment: UserPlus,
  teams: UsersRound,
  projects: FolderKanban,
  tasks: ListChecks,
  meetings: CalendarDays,
  absences: CalendarOff,
  livecon: Radio,
  academy: GraduationCap,
  glossary: BookOpen,
  skill: Target,
  objective: Flag,
  dispositif: Route,
  sanctions: Gavel,
  flash: Zap,
  settings: Settings,
  search: Search,
  youtuber: MonitorPlay,
  discord: MessageSquare,
  platform: Hash,
  division: ChevronsRight,
  note: StickyNote,
  history: History,
  sheet: FileText,
  shield: Shield,
  alert: ShieldAlert,
  add: Plus,
  edit: Pencil,
  remove: Trash2,
  close: X,
  confirm: Check,
  copy: Copy,
  link: Link2,
  filter: Filter,
  sort: ArrowUpDown,
  drag: GripVertical,
  next: ChevronRight,
  expand: ChevronDown,
  forward: ArrowRight,
  back: ArrowLeft,
  signOut: LogOut,
  light: Sun,
  dark: Moon,
  system: Monitor,
  visible: Eye,
  hidden: EyeOff,
  star: Star,
  spark: Sparkles,
  emoji: Smile,
  clock: Clock,
  deadline: AlarmClock,
  mail: Mail,
  phone: Phone,
  birthday: Cake,
  info: Info,
  warning: TriangleAlert,
  danger: CircleAlert,
  success: CircleCheck,
  failure: CircleX,
  help: CircleHelp,
  blocked: Ban,
  pending: Loader,
  checkbox: Square,
  bold: Bold,
  italic: Italic,
  underline: Underline,
  strike: Strikethrough,
  heading: Heading2,
  quote: Quote,
  bulletList: ListIcon,
  orderedList: ListOrdered,
  code: Code,
  codeBlock: SquareCode,
} as const satisfies Record<string, LucideIcon>

export type IconName = keyof typeof ICONS
