/**
 * Copy of the access matrix
 * @type {Record<string, string>}
 */

export const ACCESS_COPY = {
  title: 'Accès',
  lead: 'Les rôles, leurs fonctions et ce que chacun ouvre. Le compte administrateur garde tout, quoi qu’il arrive.',
  save: 'Enregistrer',
  preset: 'Remettre les permissions conseillées',
  presetTitle: 'Remettre les permissions conseillées ?',
  presetDescription: 'Les permissions de ce rôle sont remplacées par celles du modèle.',
  granted: 'permissions',
  grantedOne: 'permission',
  search: 'Chercher une permission',
  noMatch: 'Aucune permission ne correspond.',
  grantAll: 'Tout',
  grantNone: 'Rien',
  sensitive: 'Sensible',
  unsaved: 'Modifications non enregistrées',
  pending: 'modification',
  pendingMany: 'modifications',
  stateInherited: 'Hérité',
  stateAllowed: 'Autorisé',
  stateDenied: 'Refusé',
  inheritedYes: 'Hérité · autorisé',
  inheritedNo: 'Hérité · refusé',
  twoFactorRequired: 'Active ton A2F et desselle-la pour modifier des permissions.',
  layerGlobal: 'Tous les YouTubeurs',
  layerLabel: 'YouTubeur',
  layerLead: 'Les réglages ci-dessous ne valent que pour ce YouTubeur.',
  simulate: 'Voir ses accès depuis ce rôle',
  simulateTitle: 'Accès simulés',
  simulateLead: 'Ce que ce rôle ouvre réellement, une fois l’héritage et les refus appliqués.',
  simulateEmpty: 'Ce rôle n’ouvre rien pour l’instant.',
  memberAdd: 'Ajouter des membres',
  memberAddLead: 'Seuls les modérateurs se rattachent ici, jamais un leader ni l’administration.',
  memberAddEmpty: 'Aucun modérateur à rattacher.',
  memberRemove: 'Retirer du rôle',
  encadrementLocked: 'Seul un administrateur modifie ce niveau.',
  addFunction: 'Ajouter une fonction',
  newFunctionName: 'Nom de la fonction',
  create: 'Créer',
  cancel: 'Annuler',
  back: 'Retour',
  tabDisplay: 'Affichage',
  tabPermissions: 'Permissions',
  tabMembers: 'Membres',
  displayNameLabel: 'Nom du rôle',
  displayNameLocked: 'Le nom d’un rôle hiérarchique ne se change pas.',
  displayAccentLabel: 'Couleur',
  displayIconLabel: 'Icône',
  displayIconNone: 'Aucune icône',
  displayCategoryLabel: 'Catégorie',
  displayKindLabel: 'Emplacement',
  displaySummaryLabel: 'Description',
  deleteFunction: 'Supprimer la fonction',
  deleteFunctionTitle: 'Supprimer cette fonction ?',
  deleteFunctionLead:
    'Elle disparaît de la liste et des sélecteurs. Sans effet sur les permissions déjà accordées ailleurs.',
  deleteBlocked: 'Des modérateurs portent cette fonction, retire-les d’abord.',
  refinementLocked: 'Active la permission de page pour ouvrir ses précisions.',
  membersEmpty: 'Personne ne porte ce rôle pour l’instant.',
  membersEmptyLead: 'Affecte ce rôle depuis la fiche d’un modérateur.',
  membersManage: 'Ouvrir les modérateurs',
  perimeterTitle: 'YouTubeurs',
  perimeterLead:
    'Les fonctions ouvertes sur chaque créateur et le nombre de modérateurs rattachés.',
  perimeterFunctions: 'Fonctions ouvertes',
  perimeterMembers: 'modérateurs',
  perimeterMembersOne: 'modérateur',
  perimeterNone: 'Aucune fonction ouverte.',
  rolesHeading: 'Rôles',
  pickRolePrompt: 'Choisis un rôle pour voir son affichage, ses permissions et ses membres.',
} as const

/**
 * Copy of the second factor
 * @type {Record<string, string>}
 */

export const TWO_FACTOR_COPY = {
  title: 'Authentification à deux facteurs',
  lead: 'Elle descelle les données sensibles : adresse mail et numéro de téléphone.',
  enrolled: 'A2F active',
  notEnrolled: 'A2F inactive',
  enrol: 'Activer l’A2F',
  enrolTitle: 'Activer l’authentification à deux facteurs',
  enrolLead:
    'Scanne ce code avec ton application d’authentification, puis recopie le code affiché.',
  manualTitle: 'Impossible de scanner ?',
  manualLead: 'Saisis cette clé à la main dans ton application.',
  copySecret: 'Copier la clé',
  secretCopied: 'Clé copiée.',
  recoveryTitle: 'Codes de secours',
  recoveryLead:
    'Garde-les hors du dashboard : chacun ouvre une fois, si ton application n’est plus là.',
  recoveryLeft: 'codes de secours restants',
  recoveryLeftOne: 'code de secours restant',
  copyRecovery: 'Copier les codes',
  recoveryCopied: 'Codes copiés.',
  codeLabel: 'Code à 6 chiffres',
  codePlaceholder: '000000',
  confirm: 'Confirmer',
  confirmed: 'A2F activée.',
  unlockTitle: 'Données scellées',
  unlockLead: 'Saisis ton code d’authentification pour ouvrir les données sensibles.',
  unlock: 'Desceller',
  unlocked: 'Données descellées.',
  unlockedUntil: 'Descellé jusqu’à',
  seal: 'Resceller',
  sealed: 'Données rescellées.',
  drop: 'Désactiver l’A2F',
  dropTitle: 'Désactiver l’A2F ?',
  dropLead: 'Les données sensibles redeviennent inaccessibles et les codes de secours sont perdus.',
  dropped: 'A2F désactivée.',
  missingTitle: 'Aucune A2F sur ce compte',
  missingLead: 'Active l’authentification à deux facteurs pour ouvrir cette donnée.',
  wrongCode: 'Ce code ne correspond pas.',
  enrolmentExpired: 'Cette activation a expiré, relance-la.',
  sealedHint: 'Sous A2F',
  reveal: 'Desceller cette donnée',
} as const

/**
 * Copy of the encadrement views
 * @type {Record<string, string>}
 */

export const VIEW_COPY = {
  noCreator: 'Aucun',
  activeCreator: 'YouTubeur en cours',
  adminTitle: 'Console admin',
  adminLead: 'L’état réel du back-end, des accès et des données de Memora.',
  adminRuntime: 'Infrastructure',
  adminRuntimeLead: 'Chaque sujet, son état d’activation et sa dernière sonde.',
  adminData: 'Données',
  adminDataLead: 'Ce que la base porte aujourd’hui.',
  adminAccess: 'Accès',
  adminAccessLead: 'Comptes, sessions ouvertes et second facteur.',
  subjectOn: 'Actif',
  subjectOff: 'Inactif',
  probeMissing: 'Aucune sonde',
  environment: 'Environnement',
  runtimeDown: 'Back-end à l’arrêt',
  runtimeDownLead: 'Aucun sujet n’est activé dans la configuration de cet environnement.',
  metricAccounts: 'Comptes',
  metricSessions: 'Sessions ouvertes',
  metricTwoFactor: 'Comptes avec A2F',
  metricCreators: 'YouTubeurs',
  metricTeams: 'Équipes',
  metricProjects: 'Projets',
  metricTasks: 'Tâches',
  metricFiles: 'Fichiers',
  metricLogs: 'Entrées de journal',
  metricNotifications: 'Notifications',
} as const
