/**
 * Copy of the academy surfaces
 * @type {Record<string, string>}
 */

export const ACADEMY_COPY = {
  title: 'Marsha Academy',
  lead: 'Chaque session accueille, forme, suit et valide ses juniors jusqu’à leur autonomie.',
  glossaryTitle: 'Lexique de l’Academy',
  glossaryLead: 'Les mots du domaine, définis une fois pour toutes.',
  sessionAdd: 'Ouvrir une session',
  emptyTitle: 'Aucune session',
  emptyDescription: 'Ouvre une première session pour accueillir des juniors.',
  sessionDeleteTitle: 'Supprimer cette session ?',
  sessionDeleteDescription: 'Ses juniors, son fil et ses bilans disparaissent avec elle.',
  sessionCount: 'juniors',
  sessionCountOne: 'junior',
  trainers: 'Formateurs',
  trainersLead: 'Les modérateurs qui encadrent cette session.',
  noTrainer: 'Aucun formateur assigné',
  confidential: 'Confidentiel',
  confidentialLead:
    'Tout ce qui vit ici reste entre les personnes autorisées : organisation, retours, évaluations, incidents.',
  tabJuniors: 'Juniors',
  tabThread: 'Fil de session',
  juniorsLead: 'Chaque junior est un modérateur existant, suivi par sa fiche individuelle.',
  juniorAdd: 'Ajouter un junior',
  juniorEmptyTitle: 'Aucun junior',
  juniorEmptyDescription: 'Rattache un modérateur existant pour démarrer son suivi.',
  juniorDeleteTitle: 'Retirer ce junior ?',
  juniorDeleteDescription: 'Son suivi, ses bilans et ses moments quittent la session.',
  noMembersTitle: 'Aucun modérateur disponible',
  noMembersDescription: 'Crée d’abord une fiche de modérateur, le junior s’y rattache ensuite.',
  openMembers: 'Ouvrir les modérateurs',
  threadLead: 'Tout ce qui est prévu ou tenu, surtout ce qui se fait en autonomie.',
  eventAdd: 'Noter un moment',
  eventEmptyTitle: 'Rien de noté',
  eventEmptyDescription:
    'Note formations, bilans, entrevues et points responsables au fil de l’eau.',
  eventDeleteTitle: 'Supprimer ce moment ?',
  eventDeleteDescription: 'La trace disparaît du fil de session.',
  eventDone: 'Tenu',
  eventPlanned: 'Prévu',
  markDone: 'Marquer comme tenu',
  markPlanned: 'Remettre en prévu',
  fileTitle: 'Fiche de suivi individuelle',
  fileLead: 'Progression, bilans et moments de ce junior.',
  progression: 'Progression',
  progressionLead: 'Les formations du programme, validées au fur et à mesure.',
  noTrainingsTitle: 'Aucune formation',
  noTrainingsDescription: 'Déclare les formations du programme dans la configuration.',
  configure: 'Ouvrir la configuration',
  mandatory: 'Obligatoire',
  progress: 'formations validées',
  blocked: 'Formations obligatoires en attente',
  ready: 'Prêt à valider',
  reviews: 'Bilans vocaux',
  reviewsLead:
    'Un point d’écoute, jamais un interrogatoire : ressenti, axes concrets, puis deux objectifs minimum.',
  reviewAdd: 'Écrire un bilan',
  reviewEmptyTitle: 'Aucun bilan',
  reviewEmptyDescription:
    'Le premier bilan pose le ressenti global et les deux premiers objectifs.',
  reviewLocked: 'Les bilans de ce junior ne te sont pas ouverts.',
  reviewDeleteTitle: 'Supprimer ce bilan ?',
  reviewDeleteDescription: 'La trace écrite de ce point disparaît.',
  validate: 'Valider ce junior',
  validateTitle: 'Valider ce junior ?',
  validateDescription: 'Il sort de l’Academy et passe en modérateur autonome.',
  stop: 'Arrêter le suivi',
  stopTitle: 'Arrêter le suivi ?',
  stopDescription: 'Le junior quitte la session sans validation. Rien n’est supprimé.',
  reopen: 'Reprendre le suivi',
  lives: 'lives accompagnés',
} as const

/**
 * Labels of the academy forms
 * @type {Record<string, string>}
 */

export const ACADEMY_FIELD_COPY = {
  program: 'Programme',
  startsAt: 'Date de début',
  endsAt: 'Date de fin',
  endsAtHint: 'Laissée vide, elle est posée sur la durée la plus courte prévue.',
  status: 'État',
  summary: 'Description',
  trainers: 'Formateurs',
  account: 'Modérateur',
  trainer: 'Formateur référent',
  dispositif: 'Dispositif',
  juniorStatus: 'Suivi',
  liveCount: 'Lives accompagnés',
  juniorSummary: 'Remarques',
  kind: 'Type de moment',
  title: 'Intitulé',
  scheduledAt: 'Date et heure',
  junior: 'Junior concerné',
  notes: 'Notes',
  heldAt: 'Date du bilan',
  feeling: 'Ressenti global',
  inclusion: 'Inclusion dans l’équipe',
  speaking: 'Aisance à l’oral',
  writing: 'Clarté à l’écrit',
  reachingOut: 'Facilité à solliciter l’administration',
  understanding: 'Compréhension des informations transmises',
  technical: 'Technique et matériel',
  objectives: 'Objectifs personnels',
  strategies: 'Stratégies pour les atteindre',
  reviewSummary: 'Ce qui progresse, ce qui bloque, ce qui est décidé',
} as const
