/**
 * Copy of the academy surfaces
 * @type {Record<string, string>}
 */

export const ACADEMY_COPY = {
  railProgramme: 'Dispositif',
  railTrainer: 'Formateur',
  sessionOf: 'Session du {date}',
  untilDate: 'Jusqu’au {date}',
  title: 'Marsha Academy',
  lead: 'Chaque session accueille, forme, suit et valide ses juniors jusqu’à leur autonomie.',
  awaitingConfirmation: 'Fiche à confirmer',
  timelineTab: 'Timeline',
  timelineAdvance: 'Passer à l’étape supérieure',
  timelineAdvanced: 'Étape validée, la suivante est ouverte',
  timelineCurrent: 'En cours',
  timelineAdvanceTitle: 'Valider l’étape en cours ?',
  timelineAdvanceDescription:
    'L’étape passe en terminée à ton nom, la suivante se colore et sa tâche part chez la personne qui la porte.',
  timelineFinished: 'Toutes les étapes de cette PIM sont passées.',
  juniorTimelineEmptyTitle: 'Aucune étape sur cette timeline',
  juniorTimelineEmptyDescription:
    'La trame de PIM se déclare dans la configuration, elle se pose sur chaque junior à son arrivée.',
  timelineOwner: 'Portée par',
  timelineDue: 'Prévue le',
  timelineDoneOn: 'Passée le',
  timelineGuide: 'Marche à suivre',
  timelineGo: 'Y aller, avec le guide',
  timelineLocks: {
    notStarted:
      'La PIM n’est pas encore lancée. Elle démarre quand un Responsable passe la session En cours.',
    awaitingReview:
      'L’étape suivante s’ouvre avec la validation du bilan de fin de période, pas depuis la timeline.',
    awaitingDecision:
      'Le bilan est déposé : la timeline est en pause jusqu’à la décision du Responsable.',
    standby:
      'Période 1 achevée. La période 2 démarre pour toute la promotion en même temps, rien n’est bloqué en attendant.',
    closed: 'Ce junior n’est plus en formation, sa timeline est figée.',
  },
  launch: 'Lancer la PIM',
  launchTitle: 'Lancer la PIM maintenant ?',
  launchDescription:
    'La session passe En cours. La timeline de chaque junior démarre aujourd’hui et les premières tâches partent chez les Formateurs.',
  launched: 'PIM lancée',
  launchMissingTrainer:
    'Un junior confirmé n’a pas encore de Formateur. Attribue-lui en un avant de passer la PIM En cours.',
  glossaryTitle: 'Lexique de l’Academy',
  glossarySearch: 'Chercher un mot',
  glossaryEmpty: 'Aucun mot ne correspond.',
  glossaryLead: 'Les mots du domaine, définis une fois pour toutes.',
  tabSessions: 'Sessions',
  tabGlossary: 'Lexique',
  sessionAdd: 'Ouvrir une session',
  emptyTitle: 'Aucune session',
  emptyDescription: 'Ouvre une première session pour accueillir des juniors.',
  sessionDeleteTitle: 'Supprimer cette session ?',
  sessionDeleteDescription: 'Ses juniors, son fil et ses bilans disparaissent avec elle.',
  sessionCount: 'juniors',
  sessionCountOne: 'junior',
  trainers: 'Formateurs',
  trainersLead: 'Les modérateurs qui encadrent cette session.',
  noTrainer: 'Aucun formateur assigné',
  confidential: 'Confidentiel',
  confidentialLead:
    'Tout ce qui vit ici reste entre les personnes autorisées : organisation, retours, évaluations, incidents.',
  tabJuniors: 'Juniors',
  tabTimeline: 'Timeline',
  tabCalendar: 'Calendrier',
  tabMissions: 'Missions',
  tabThread: 'Fil de session',
  juniorsLead: 'Chaque junior est un modérateur existant, suivi par sa fiche individuelle.',
  timelineLead: 'Les étapes de la trame, en retard, en cours ou franchies, junior par junior.',
  timelineSessionWide: 'Avant l’arrivée des juniors',
  timelineEmptyTitle: 'Aucune étape',
  timelineEmptyDescription: 'La trame se configure depuis /configuration/etapes-pim.',
  stepValidate: 'Marquer comme franchie',
  stepReopen: 'Rouvrir cette étape',
  stateDone: 'Franchie',
  stateLate: 'En retard',
  stateCurrent: 'En cours',
  stateIdle: 'À venir',
  juniorAdd: 'Ajouter un junior',
  juniorEmptyTitle: 'Aucun junior',
  juniorEmptyDescription: 'Rattache un modérateur existant pour démarrer son suivi.',
  juniorDeleteTitle: 'Retirer ce junior ?',
  juniorDeleteDescription: 'Son suivi, ses bilans et ses moments quittent la session.',
  noMembersTitle: 'Aucun modérateur disponible',
  noMembersDescription: 'Crée d’abord une fiche de modérateur, le junior s’y rattache ensuite.',
  openMembers: 'Ouvrir les modérateurs',
  threadLead: 'Tout ce qui est prévu ou tenu, surtout ce qui se fait en autonomie.',
  eventAdd: 'Noter un moment',
  eventEmptyTitle: 'Rien de noté',
  eventEmptyDescription:
    'Note formations, bilans, entrevues et points responsables au fil de l’eau.',
  eventDeleteTitle: 'Supprimer ce moment ?',
  eventDeleteDescription: 'La trace disparaît du fil de session.',
  eventDone: 'Tenu',
  eventPlanned: 'Prévu',
  markDone: 'Marquer comme tenu',
  markPlanned: 'Remettre en prévu',
  fileTitle: 'Fiche de suivi individuelle',
  fileLead: 'Progression, bilans et moments de ce junior.',
  progression: 'Progression',
  progressionLead: 'Les formations du programme, validées au fur et à mesure.',
  noTrainingsTitle: 'Aucune formation',
  noTrainingsDescription: 'Déclare les formations du programme dans la configuration.',
  configure: 'Ouvrir la configuration',
  groupRunning: 'En cours',
  groupFinished: 'Terminées',
  openCatalogue: 'Ouvrir le catalogue',
  openSessions: 'Ouvrir les sessions',
  mandatory: 'Obligatoire',
  progress: 'formations validées',
  blocked: 'Formations obligatoires en attente',
  ready: 'Prêt à valider',
  reviews: 'Bilans vocaux',
  reviewsLead:
    'Un point d’écoute, jamais un interrogatoire : ressenti, compte-rendu, puis avis proposé.',
  reviewAdd: 'Écrire un bilan',
  reviewEmptyTitle: 'Aucun bilan',
  reviewEmptyDescription: 'Le premier bilan pose le ressenti global et le compte-rendu du vocal.',
  reviewLocked: 'Les bilans de ce junior ne te sont pas ouverts.',
  reviewDeleteTitle: 'Supprimer ce bilan ?',
  reviewDeleteDescription: 'La trace écrite de ce point disparaît.',
  reviewSubmit: 'Soumettre à décision',
  reviewValidate: 'Valider ce bilan',
  reviewValidateTitle: 'Valider ce bilan ?',
  reviewValidateDescription: 'La FSI avance à l’étape suivante selon l’avis proposé.',
  reviewReject: 'Refuser ce bilan',
  reviewRejectTitle: 'Refuser ce bilan ?',
  reviewRejectDescription: 'Le Formateur devra rédiger un nouveau bilan.',
  validate: 'Valider ce junior',
  validateTitle: 'Valider ce junior ?',
  validateDescription: 'Il sort de l’Academy et passe en modérateur autonome.',
  stop: 'Arrêter le suivi',
  stopTitle: 'Arrêter le suivi ?',
  stopDescription: 'Le junior quitte la session sans validation. Rien n’est supprimé.',
  reopen: 'Reprendre le suivi',
  lives: 'lives accompagnés',
  tabInformations: 'Informations',
  tabCompetences: 'Compétences',
  tabNotes: 'Notes',
  tabObjectives: 'Objectifs',
  tabReviews: 'Bilans',
  skillsLead: 'Le pourcentage de maîtrise de chaque compétence de la fonction et du dispositif.',
  noteAdd: 'Poser une note',
  noteEmptyTitle: 'Aucune note',
  noteEmptyDescription: 'Remarque, observation, avertissement ou compliment, au fil de l’eau.',
  noteLocked: 'Les notes de ce junior ne te sont pas ouvertes.',
  noteDeleteTitle: 'Supprimer cette note ?',
  noteDeleteDescription: 'La trace disparaît de la FSI.',
  objectiveAdd: 'Fixer un objectif',
  objectiveEmptyTitle: 'Aucun objectif',
  objectiveEmptyDescription: 'Les objectifs personnels se fixent une fois la pratique commencée.',
  objectiveLockedTitle: 'Objectifs verrouillés',
  objectiveLockedDescription: 'Ils se déverrouillent une fois le premier bilan validé.',
  objectiveSeeReviews: 'Voir les bilans',
  objectiveDeleteTitle: 'Supprimer cet objectif ?',
  objectiveDeleteDescription: 'Il disparaît de la FSI.',
  myTrainingsTitle: 'Mes formations',
  myTrainingsLead: 'Les formations de ta fonction et de ton dispositif, à ton rythme.',
  myTrainingsNoFsiTitle: 'Aucune FSI active',
  myTrainingsNoFsiDescription: 'Les formations apparaissent une fois ton suivi commencé.',
  myTrainingsEmptyTitle: 'Aucune formation',
  myTrainingsEmptyDescription: 'Rien n’est encore déclaré pour ta fonction et ton dispositif.',
  trainingStart: 'Démarrer',
  trainingResume: 'Reprendre',
  trainingRestart: 'Recommencer',
  trainingAbandon: 'Abandonner',
  trainingComplete: 'Terminer',
  trainingAttempts: 'tentatives',
  trainingAttemptsOne: 'tentative',
  trainingDurationUnit: 'min',
  trainingContentTitle: 'Contenu',
  trainingContentLead: 'Le déroulé de la formation, chapitre par chapitre.',
  viewContent: 'Voir le contenu',
  noContentTitle: 'Contenu à venir',
  noContentDescription: 'Rien n’est encore rédigé pour cette formation.',
  takeQuiz: 'Faire le quiz',
  quizSubmit: 'Valider mes réponses',
  quizResultSuffix: 'bonnes réponses',
  quizAnswered: 'Répondu',
  quizQuestionCount: 'questions',
  quizQuestionCountOne: 'question',
  inviteCopyLink: 'Copier le lien d’admission',
  inviteCopied: 'Lien copié',
  mandatoryPending: 'Une formation obligatoire n’est pas encore terminée.',
  accompaniedTitle: 'Lives où il était présent',
  accompaniedEmpty: 'Aucun live compté pour l’instant.',
} as const

/**
 * Labels of the academy forms
 * @type {Record<string, string>}
 */

export const ACADEMY_FIELD_COPY = {
  function: 'Fonction',
  startsAt: 'Date de début',
  endsAt: 'Date de fin',
  endsAtHint: 'Laissée vide, elle est posée sur la durée la plus courte prévue.',
  status: 'État',
  summary: 'Description',
  trainers: 'Formateurs',
  account: 'Modérateur',
  trainer: 'Formateur référent',
  dispositif: 'Dispositif',
  juniorStatus: 'Suivi',
  liveCount: 'Lives accompagnés',
  bonusLives: 'Lives bonus',
  bonusLivesHint: 'Ouverts sur décision du Responsable, jusqu’au maximum réglé.',
  juniorSummary: 'Remarques',
  kind: 'Type de moment',
  title: 'Intitulé',
  scheduledAt: 'Date et heure',
  junior: 'Junior concerné',
  notes: 'Notes',
  heldAt: 'Date du bilan',
  feeling: 'Ressenti global',
  reviewStage: 'Étape du bilan',
  durationMinutes: 'Durée du vocal (minutes)',
  advice: 'Avis proposé',
  reviewSummary: 'Ce qui progresse, ce qui bloque, ce qui est décidé',
  decisionNote: 'Note de décision',
  noteStage: 'Étape concernée',
  noteKind: 'Type de note',
  noteBody: 'Contenu',
  objectiveTitle: 'Intitulé',
  objectiveDescription: 'Détail',
  objectiveDueAt: 'Échéance',
  objectiveStatus: 'Statut',
  skillPercent: 'Maîtrise',
} as const

/**
 * Copy of the public admission form
 * @type {Record<string, string>}
 */

export const ADMISSION_COPY = {
  title: 'Admission Marsha Academy',
  subtitle: 'Rejoins une session en cours de recrutement.',
  submit: 'Envoyer ma candidature',
  pending: 'Envoi…',
  successTitle: 'Candidature envoyée',
  successDescription: 'Un Formateur vérifie ton dossier, à très vite en vocal !',
  invalidTitle: 'Lien invalide',
  invalidDescription:
    'Ce lien d’admission n’existe plus, a expiré ou a atteint son nombre d’utilisations.',
  rejected: 'Cette candidature n’a pas pu être enregistrée. Vérifie ton identifiant Discord.',
  consentLabel: 'J’accepte la conservation de mes données',
} as const

/**
 * Labels of the public admission form
 * @type {Record<string, string>}
 */

export const ADMISSION_FIELD_COPY = {
  displayName: 'Pseudo',
  dispositif: 'Dispositif souhaité',
} as const

/**
 * Copy of the training content editor
 * @type {Record<string, string>}
 */

export const TRAINING_CONTENT_COPY = {
  title: 'Contenu de la formation',
  lead: 'Le contenu se découpe en chapitres, chacun porté par un ou plusieurs blocs.',
  questionLabel: 'Question',
  chapterAdd: 'Ajouter un chapitre',
  chapterEmptyTitle: 'Aucun chapitre',
  chapterEmptyDescription: 'Ajoute un premier chapitre pour commencer le contenu.',
  chapterDeleteTitle: 'Supprimer ce chapitre ?',
  chapterDeleteDescription: 'Ses blocs et ses questions disparaissent avec lui.',
  blockAdd: 'Ajouter un bloc',
  blockEmptyTitle: 'Aucun bloc',
  blockEmptyDescription: 'Ajoute un texte ou un quiz dans ce chapitre.',
  blockDeleteTitle: 'Supprimer ce bloc ?',
  blockDeleteDescription: 'Son contenu disparaît du chapitre.',
  questionAdd: 'Ajouter une question',
  questionEmptyTitle: 'Aucune question',
  questionEmptyDescription: 'Ajoute une première question à ce quiz.',
  questionDeleteTitle: 'Supprimer cette question ?',
  questionDeleteDescription:
    'Les réponses déjà données restent enregistrées, la question disparaît du quiz.',
  choiceAdd: 'Ajouter une réponse',
  choiceEmptyTitle: 'Aucune réponse',
  choiceEmptyDescription: 'Ajoute au moins deux réponses, dont une correcte.',
  choiceDeleteTitle: 'Supprimer cette réponse ?',
  choiceDeleteDescription: 'Elle disparaît de la question.',
} as const

/**
 * Labels of the training content forms
 * @type {Record<string, string>}
 */

export const TRAINING_CONTENT_FIELD_COPY = {
  chapterTitle: 'Titre',
  blockKind: 'Type de bloc',
  blockBody: 'Texte',
  questionPrompt: 'Question',
  questionMultiple: 'Plusieurs bonnes réponses',
  choiceLabel: 'Réponse',
  choiceCorrect: 'Bonne réponse',
} as const

/**
 * Copy of the guided walkthrough
 * @type {Record<string, string>}
 */

export const GUIDE_COPY = {
  counter: 'Étape {index} sur {total}',
  previous: 'Précédent',
  next: 'Suivant',
  finish: 'C’est compris',
  close: 'Fermer le guide',
} as const

/**
 * Copy of the interactive courses
 * @type {Record<string, string | ((value: number) => string)>}
 */

export const COURSE_COPY = {
  catalogTitle: 'Parcours',
  catalogLead:
    'Chaque formation se lit, se joue et se vérifie ici. Tout se valide par des exercices.',
  indispensableTitle: 'Les indispensables',
  indispensableLead: 'À terminer pendant la période de découverte.',
  secondaryTitle: 'Pour aller plus loin',
  secondaryLead: 'Elles apparaissent avec la période de pratique.',
  consoleTitle: 'Autres formations',
  minutes: (value: number) => `${value} min`,
  exercises: (value: number) => `${value} ${value > 1 ? 'exercices' : 'exercice'}`,
  progress: (done: number, total: number) => `${done} sur ${total}`,
  exercisesUnit: 'exercices réussis',
  start: 'Commencer',
  resume: 'Reprendre',
  review: 'Revoir',
  done: 'Terminée',
  emptyTitle: 'Aucune formation pour ta fonction',
  emptyDescription: 'Les formations de ta fonction arrivent, elles apparaîtront ici.',
  chapters: 'Chapitres',
  back: 'Toutes les formations',
  check: 'Vérifier',
  retry: 'Réessayer',
  saving: 'Enregistrement…',
  passed: 'Réussi',
  failed: 'Pas encore',
  partial: 'Presque',
  replay: 'Rejouer',
  next: 'Suivant',
  pick: 'Choisis ton geste',
  yourAnswer: 'Ta réponse',
  expert: 'Réponse de l’expert',
  showExpert: 'Voir la réponse de l’expert',
  openPlaceholder: 'Écris ta réponse',
  commandPlaceholder: '!commande',
  hint: 'Indice',
  showHint: 'Voir un indice',
  bank: 'Mots proposés',
  fillPick: 'Choisir',
  sortHint: 'Glisse chaque élément dans sa colonne, ou touche-le puis touche la colonne.',
  orderHint: 'Glisse les éléments dans le bon ordre, ou utilise les flèches.',
  moveUp: 'Monter',
  moveDown: 'Descendre',
  unsorted: 'À classer',
  tip: 'Astuce',
  warning: 'Attention',
  rule: 'Règle',
  simulationStep: (current: number, total: number) => `Situation ${current} sur ${total}`,
  simulationBegin: 'Lancer la simulation',
  bravo: 'Bravo, cette formation est accomplie avec brio !',
  anotherWaiting: 'Une autre formation t’attend !',
  completeCta: 'Voir les autres formations',
  nextChapter: 'Chapitre suivant',
  nextChapterTo: (index: number, title: string) => `Passer au chapitre ${index} : ${title}`,
  nextPage: 'Page suivante',
  you: 'Toi',
  tourAuto: 'Activer le mode Auto',
  tourStop: 'Arrêter le mode Auto',
  tourList: 'Blocs de la Vue Modérateur',
  ladder: 'Hiérarchie décisionnelle',
  ladderEmpty: 'Personne pour l’instant',
  liveconLevel: (level: number) => `Livecon ${level}`,
  liveconPanel: (name: string) => `Panel de sanctions en ${name}`,
  liveconNoPanel: 'Aucun panel de sanctions n’est encore saisi pour ce niveau.',
  sceneReplay: 'Rejouer la scène',
  exampleGood: 'À reprendre',
  exampleBad: 'À proscrire',
  runLabel: (index: number) => `Cas ${index}`,
  runPlaying: (index: number, total: number) => `Cas ${index} sur ${total}`,
  runReplay: 'Rejouer',
  runPickTitle: 'Quelle prise en charge est la plus adéquate ?',
  runPick: (index: number) => `Cas ${index}`,
  branchingRestart: 'Recommencer la discussion',
  introKicker: 'Formation',
  introTitle: (name: string) => `Bienvenue dans la Formation « ${name} »`,
  objective: 'Objectif',
  outlineTitle: 'Découpage',
  outlineCount: (count: number) =>
    `La formation se découpe en ${count} ${count > 1 ? 'chapitres' : 'chapitre'}, ${count > 1 ? 'munis respectivement' : 'muni'} de plusieurs étapes.`,
  caseStudy: 'Cas d’étude démonstratif',
  startChapter: (title: string) => `Chapitre 1 : ${title}`,
  endTitle: 'FIN.',
  endBody: 'Tu as terminé ta formation.',
  endReplay: 'Tu peux bien évidemment la rejouer autant de fois que nécessaire.',
  endNotified:
    'Ton Formateur, ainsi que les Responsables ont été prévenus de ton acquis de formation.',
  feedbackTitle: 'Qu’en as-tu pensé ?',
  feedbackLead: 'Merci de noter le contenu, et la fluidité de la formation sur 10.',
  feedbackHonest: 'Sois honnête : nos formations évoluent en permanence.',
  contentScale: 'Qualité du contenu',
  contentLow: 'Rien compris',
  contentHigh: 'Excellente',
  fluencyScale: 'Fluidité',
  fluencyLow: 'Pas du tout fluide',
  fluencyHigh: 'Parfaitement fluide',
  comment: 'Un commentaire constructif, si tu le souhaites',
  commentPlaceholder: 'Ce qui t’a aidé, ce qui t’a perdu…',
  backToTrainings: 'Retourner à la page de Formations',
  cheer: 'Félicitations !',
  stamp: 'Formation achevée',
  nextLocked: 'Réussis les exercices de ce chapitre pour continuer.',
  chapterCount: (current: number, total: number) => `Chapitre ${current} sur ${total}`,
  stepWelcome: 'Bienvenue',
  welcomeHello: 'Bienvenue !',
  welcomeToday: (title: string) => `Aujourd’hui, nous allons aborder « ${title} ».`,
  welcomeGoal: 'À la fin de ce chapitre, tu sauras le mettre en pratique sur un vrai live.',
  welcomeSteps: 'Au programme',
  slideHint: 'Slide pour continuer le chapitre',
  slideLocked: 'Réussis cette étape pour continuer',
  stepCounter: (current: number, total: number) => `Étape ${current} sur ${total}`,
  stepsLabel: 'Étapes du chapitre',
  stepKinds: {
    text: 'Lecture',
    callout: 'À retenir',
    chat: 'Exemple',
    discord: 'Exemple Discord',
    discordExample: 'Exemple Discord',
    steps: 'Marche à suivre',
    keypoints: 'Points clés',
    diagram: 'Schéma',
    compare: 'À faire, à éviter',
    demo: 'Démonstration',
    tour: 'Visite guidée',
    focus: 'Zoom',
    hierarchy: 'Hiérarchie',
    livecon: 'Livecon',
    disclosure: 'Pour aller plus loin',
    quiz: 'Quiz',
    fill: 'Texte à trous',
    sort: 'Classement',
    order: 'Remise en ordre',
    simulation: 'Simulation',
    case: 'Cas d’étude',
    command: 'Commande',
    scene: 'Mise en situation',
    compareRuns: 'Comparaison',
    branching: 'Histoire à choix',
  } as Record<string, string>,
  simulationFinish: 'Terminer la simulation',
  simulationReplay: 'Rejouer la simulation',
  demoStart: 'Lancer la démo',
  demoNext: 'Étape suivante',
  demoPrev: 'Précédent',
  demoReplay: 'Rejouer la démo',
  demoStep: (current: number, total: number) => `Étape ${current} sur ${total}`,
  demoActions: 'Actions du modérateur',
  demoDeleted: 'Message supprimé par un modérateur',
  demoComposer: 'Écris ta commande',
  demoGesture: {
    delete: 'Supprimer',
    warn: 'Avertir',
    timeout: 'Timeout',
    ban: 'Bannir',
  },
  demoTagWarn: 'Avertissement',
  demoTagBan: 'Banni',
  demoTagTimeout: (duration: string) => `Timeout ${duration}`,
  chatLive: 'En direct',
  chatFlagged: 'Message à traiter',
  chatEmpty: 'Le chat est calme.',
  unlockedIn: 'Verrouillée',
  attemptsWrong: 'À revoir',
} as const

/**
 * Copy of the training reviews
 * @type {Record<string, string>}
 */

export const TRAINING_FEEDBACK_COPY = {
  title: 'Avis des modérateurs',
  lead: 'Ce qu’ils ont pensé de la formation en la terminant. Visible de l’Administration et des Responsables.',
  content: 'Qualité du contenu',
  fluency: 'Fluidité',
  outOfTen: '{value} / 10',
  empty: 'Aucun avis pour l’instant.',
  noComments: 'Aucun commentaire écrit.',
} as const
