// Narrows a board route to one creator, the API reading it as a query parameter
const withScope = (path: string, youtuberId?: string): string =>
  youtuberId ? `${path}?youtubeur=${encodeURIComponent(youtuberId)}` : path

/**
 * Single source of every API path
 * @type {Record<string, string | ((...parts: string[]) => string)>}
 */

export const API_ROUTES = {
  reference: (section: string) => `/api/configuration/${section}`,
  referenceItem: (section: string, id: string) => `/api/configuration/${section}/${id}`,
  referenceOrder: (section: string) => `/api/configuration/${section}/ordre`,
  members: '/api/moderateurs',
  member: (id: string) => `/api/moderateurs/${id}`,
  memberNotes: (id: string) => `/api/moderateurs/${id}/notes`,
  memberSocials: (id: string) => `/api/moderateurs/${id}/reseaux`,
  social: (id: string) => `/api/reseaux/${id}`,
  files: '/api/fichiers',
  memberAccess: (id: string) => `/api/moderateurs/${id}/acces`,
  note: (id: string) => `/api/notes/${id}`,
  projects: '/api/projets',
  project: (id: string) => `/api/projets/${id}`,
  projectCommunications: (id: string) => `/api/projets/${id}/communications`,
  communication: (id: string) => `/api/communications/${id}`,
  tasks: '/api/taches',
  task: (id: string) => `/api/taches/${id}`,
  meetings: '/api/reunions',
  meeting: (id: string) => `/api/reunions/${id}`,
  meetingAttendees: (id: string) => `/api/reunions/${id}/participants`,
  meetingTopics: (id: string) => `/api/reunions/${id}/sujets`,
  meetingTopic: (id: string) => `/api/sujets/${id}`,
  absences: '/api/absences',
  absence: (id: string) => `/api/absences/${id}`,
  livecon: '/api/livecon',
  sanctions: (youtuberId: string, levelId?: string) =>
    `/api/sanctions?youtubeur=${youtuberId}${levelId ? `&niveau=${levelId}` : ''}`,
  sanctionOffense: (id: string) => `/api/sanctions/${id}`,
  sanctionLadder: (id: string) => `/api/sanctions/${id}/paliers`,
  calendar: (from: string, to: string, sessionId?: string) =>
    `/api/calendrier?debut=${encodeURIComponent(from)}&fin=${encodeURIComponent(to)}` +
    (sessionId ? `&session=${encodeURIComponent(sessionId)}` : ''),
  calendarEntries: '/api/calendrier',
  calendarEntry: (id: string) => `/api/calendrier/${id}`,
  academy: '/api/academy',
  session: (id: string) => `/api/academy/${id}`,
  sessionJuniors: (id: string) => `/api/academy/${id}/juniors`,
  sessionSteps: (id: string) => `/api/academy/${id}/etapes`,
  junior: (id: string) => `/api/juniors/${id}`,
  juniorTrainings: (id: string) => `/api/juniors/${id}/formations`,
  juniorReviews: (id: string) => `/api/juniors/${id}/bilans`,
  juniorSkills: (id: string) => `/api/juniors/${id}/competences`,
  juniorNotes: (id: string) => `/api/juniors/${id}/notes`,
  juniorObjectives: (id: string) => `/api/juniors/${id}/objectifs`,
  juniorObjectivesOrder: (id: string) => `/api/juniors/${id}/objectifs/ordre`,
  step: (id: string) => `/api/etapes/${id}`,
  review: (id: string) => `/api/bilans/${id}`,
  reviewSubmit: (id: string) => `/api/bilans/${id}/soumettre`,
  reviewDecision: (id: string) => `/api/bilans/${id}/decision`,
  juniorNote: (id: string) => `/api/notes-fsi/${id}`,
  objective: (id: string) => `/api/objectifs/${id}`,
  myTrainingProgress: (id: string) => `/api/formations/${id}/progression`,
  myTrainingContent: (id: string) => `/api/formations/${id}/contenu`,
  admission: (token: string) => `/api/admission/${token}`,
  trainingChapters: (id: string) => `/api/formations/${id}/chapitres`,
  trainingChaptersOrder: (id: string) => `/api/formations/${id}/chapitres/ordre`,
  chapter: (id: string) => `/api/chapitres/${id}`,
  chapterBlocks: (id: string) => `/api/chapitres/${id}/blocs`,
  chapterBlocksOrder: (id: string) => `/api/chapitres/${id}/blocs/ordre`,
  block: (id: string) => `/api/blocs/${id}`,
  blockQuestions: (id: string) => `/api/blocs/${id}/questions`,
  blockQuestionsOrder: (id: string) => `/api/blocs/${id}/questions/ordre`,
  blockQuiz: (id: string) => `/api/blocs/${id}/quiz`,
  question: (id: string) => `/api/questions/${id}`,
  questionChoices: (id: string) => `/api/questions/${id}/choix`,
  questionChoicesOrder: (id: string) => `/api/questions/${id}/choix/ordre`,
  choice: (id: string) => `/api/choix/${id}`,
  recruitments: '/api/recrutements',
  recruitment: (id: string) => `/api/recrutements/${id}`,
  recruitmentCandidates: (id: string) => `/api/recrutements/${id}/candidats`,
  recruitmentSteps: (id: string) => `/api/recrutements/${id}/etapes`,
  recruitmentInstructions: (id: string) => `/api/recrutements/${id}/consignes`,
  candidate: (id: string) => `/api/candidats/${id}`,
  candidateReview: (id: string) => `/api/candidats/${id}/bilan`,
  candidateColumn: (id: string) => `/api/candidats/${id}/colonne`,
  candidateComments: (id: string) => `/api/candidats/${id}/commentaires`,
  candidateComment: (id: string) => `/api/commentaires/${id}`,
  recruitmentStep: (id: string) => `/api/etapes-recrutement/${id}`,
  recruitmentStepStatus: (id: string) => `/api/etapes-recrutement/${id}/statut`,
  teams: (youtuberId?: string) => withScope('/api/equipes', youtuberId),
  team: (id: string, youtuberId?: string) => withScope(`/api/equipes/${id}`, youtuberId),
  access: '/api/acces',
  profile: '/api/parametres',
  board: '/api/tableau',
  search: '/api/recherche',
} as const

/**
 * Single source of every client cache key
 * @type {Record<string, (...parts: string[]) => string>}
 */

export const CACHE_KEYS = {
  reference: (section: string) => `reference:${section}`,
  members: () => 'members',
  member: (id: string) => `member:${id}`,
  projects: () => 'projects',
  project: (id: string) => `project:${id}`,
  tasks: () => 'tasks',
  task: (id: string) => `task:${id}`,
  meetings: () => 'meetings',
  meeting: (id: string) => `meeting:${id}`,
  absences: () => 'absences',
  livecon: () => 'livecon',
  sanctions: (youtuberId: string) => `sanctions:${youtuberId}`,
  teams: () => 'teams',
  calendar: (from: string, to: string) => `calendar:${from}:${to}`,
  recruitments: () => 'recruitments',
  recruitment: (id: string) => `recruitment:${id}`,
  sessions: () => 'academy:sessions',
  session: (id: string) => `academy:session:${id}`,
  junior: (id: string) => `academy:junior:${id}`,
  access: () => 'access',
  profile: () => 'profile',
  search: (term: string) => `search:${term}`,
} as const
