/**
 * Copy of the system screens
 * @type {Record<string, string>}
 */

export const SYSTEM_COPY = {
  title: 'Système',
  lead: 'L’état réel de l’infrastructure sur laquelle Memora tourne.',
  storageTitle: 'Stockage',
  storageLead: 'Ce que le magasin de fichiers garde aujourd’hui, destination par destination.',
  storageUsage: 'Occupation',
  storageUsageLead: 'Tout ce que Memora a déposé, portraits et bannières compris.',
  storageBuckets: 'Destinations',
  storageBucketsLead: 'Chaque destination déclarée, sa visibilité et son plafond de dépôt.',
  storageEmptyTitle: 'Aucun fichier stocké',
  storageEmptyLead: 'Le magasin se remplit au premier portrait ou fichier déposé.',
  storagePublic: 'Public',
  storagePrivate: 'Privé',
  storageCeiling: 'Plafond',
  storageUndeclared: 'Non déclarée',
  metricObjects: 'Objets',
  metricWeight: 'Poids total',
  metricBuckets: 'Destinations occupées',
  journalTitle: 'Journaux',
  journalLead: 'Les faits que Memora garde, du plus récent au plus ancien.',
  journalRecent: 'Derniers évènements',
  journalRecentLead: 'La trace de ce que l’équipe et le système ont fait.',
  journalEmptyTitle: 'Aucun évènement',
  journalEmptyLead: 'Le journal se remplit dès la première action enregistrée.',
  metricEntries: 'Entrées',
  metricRetention: 'Conservation',
  retentionDays: 'jours',
  queuesTitle: 'Files de jobs',
  queuesLead: 'Les traitements que Memora fait tourner en dehors d’une requête.',
  queuesDeclared: 'Jobs déclarés',
  queuesDeclaredLead: 'Chaque job enregistré, sa cadence et ses réglages propres.',
  queuesEmptyTitle: 'Aucun job déclaré',
  queuesEmptyLead: 'Déclare un job dans le registre pour le voir tourner ici.',
  queuesSchedule: 'Cadence',
  queuesOnDemand: 'À la demande',
  queuesAttempts: 'tentatives',
  queuesConcurrency: 'workers',
  probesTitle: 'Sondes',
  probesLead: 'L’état de chaque sujet du back-end, tel que la dernière sonde l’a vu.',
  probesSubjects: 'Sujets',
  probesSubjectsLead: 'Activation, dernière sonde et latence mesurée.',
  analyticsTitle: 'GA4',
  analyticsLead: 'L’audience du dashboard, une fois la propriété Analytics raccordée.',
  analyticsWip: 'Aucune propriété Google Analytics n’est encore raccordée à Memora.',
} as const
