import { readdirSync, readFileSync, mkdirSync, writeFileSync, statSync } from 'node:fs'
import { dirname, join, relative } from 'node:path'
import { fileURLToPath } from 'node:url'

// Repository root
const ROOT = dirname(dirname(fileURLToPath(import.meta.url)))
const API_DIR = join(ROOT, 'src/app/api')
const OUTPUT = join(ROOT, 'src/generated/openapi/manifest.ts')

// Serves the document
const SELF = join(API_DIR, 'openapi/route.ts')

// Exported HTTP verbs
const METHOD_PATTERN = /export const (GET|POST|PUT|PATCH|DELETE)\b/g

/**
 * Every route file
 * @param {string} dir - Folder walked
 * @return {string[]} - Absolute paths
 */

const routeFiles = (dir: string): string[] =>
  readdirSync(dir).flatMap((entry) => {
    const path = join(dir, entry)
    if (statSync(path).isDirectory()) return routeFiles(path)

    return entry === 'route.ts' ? [path] : []
  })

/**
 * OpenAPI path of a file
 * @param {string} file - Route file
 * @return {string} - /api/... with {params}
 */

const pathOf = (file: string): string =>
  `/${relative(join(ROOT, 'src/app'), dirname(file))}`
    .replace(/\[\.\.\.(\w+)\]/g, '{$1}')
    .replace(/\[(\w+)\]/g, '{$1}')

// Static imports only
const entries = routeFiles(API_DIR)
  .filter((file) => file !== SELF)
  .sort()
  .flatMap((file) => {
    const methods = [...readFileSync(file, 'utf8').matchAll(METHOD_PATTERN)].map((m) => m[1])
    if (methods.length === 0) return []

    const specifier = `@/${relative(join(ROOT, 'src'), file).replace(/\.ts$/, '')}`

    return [{ path: pathOf(file), specifier, methods }]
  })

const lines = [
  '// Generated by scripts/generate-openapi-manifest.ts, never edited by hand',
  "import type { RouteHandler } from '@/core/lib/http/route'",
  ...entries.map((entry, index) => `import * as route${index} from '${entry.specifier}'`),
  '',
  'export const OPENAPI_MANIFEST: { path: string; handlers: Record<string, RouteHandler> }[] = [',
  ...entries.map(
    (entry, index) =>
      `  { path: '${entry.path}', handlers: { ${entry.methods.map((method) => `${method}: route${index}.${method}`).join(', ')} } },`
  ),
  ']',
  '',
]

mkdirSync(dirname(OUTPUT), { recursive: true })
writeFileSync(OUTPUT, lines.join('\n'))
console.log(`OpenAPI manifest: ${entries.length} routes`)
